spring.datasource.url=jdbc:mysql://inpulse-database-api.mysql.database.azure.com:3306/api?createDatabaseIfNotExist=true
spring.datasource.username=AdminInpulse
spring.datasource.password=Fiap#123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.application.name=Inpulse-DataBase
springdoc.swagger-ui.path=/